### PR TITLE
Demuxalot: Limit number of parallel jobs

### PR DESCRIPTION
**Pull request by mschilli87**
PR #46 paves the way to upgrade Demuxalot to the latest version (v. 0.4.0).
However, that version includes support for parallel processing via `joblib.parallel`  with a default value for `n_jobs` of `-1`, resulting in the use of all CPUs/threads provided by the system.
This PR adds a commit adding the `-p`/`--nproc` parameter (cf. Vireo) to override that default on top of PR #46.
Since Demuxalot's default behaviour could potentially result in bad surprises, the default value was changed from `-1` to `1` in the wrapper script. Thus, existing pipelines using Demuxafy's `Demuxalot.py` script won't require any changes to avoid unexpected CPU loads.

---
closes #46

### CODE REVIEW

**Comment by mschilli87** [comment]
@drneavin: Just to clarify: If you merge this along upgrading the bundled Demuxalot to version >=0.4.1, PR #46 will be closed automatically and I can convert PR #48 from draft to ready, which would finally enable running Demuxafy on non-CellRanger data.

**Comment by mschilli87** [comment]
@drneavin: Any update on this? Did you encounter issues with my suggested changes or are you simply still busy with other things? Let me kniw if I can help somehow. Using a custom build python module on top of singularity is kinda painful, so I'd happily do more work to get a new container with those changes (and PR #48) included.

**Comment by drneavin** [comment]
Hi @mschilli87, yes sorry it's just been a busy time on my end. I'm getting one thing off my plate at the end of the week that has been taking ~50% of my time so hoping I can get to this early next week. Will take some time to build it and test it but I'll let you know when I start the process

**Comment by drneavin** [comment]
Hi @mschilli87 , I'm trying to attend to all the Demuxafy updates this week and wanted to clarify how you think it would be best to proceed with these changes. To be clear, all changes in pull request #46 are now included here so there is no reason to merge #46 before #47?

And then #48 can be merged as well since it seems there shouldn't be any conflicts between them?

**Comment by mschilli87** [comment]
@drneavin
> To be clear, all changes in pull request #46 are now included here so there is no reason to merge #46 before #47?

Yes and yes. 

> And then #48 can be merged as well since it seems there shouldn't be any conflicts between them?

There might be a minor conflicts but I can either fix those in #48 once this is merged or rebase #48 on this branch now so you only have a single PR including all changes at once.

**Pull request merged**
